export const QUIZ_RETRY = 'QUIZ_RETRY';
export const PROCESS_QUIZ_ERROR = 'PROCESS_QUIZ_ERROR';
export const FETCHED_QUIZZES = 'FETCHED_QUIZZES';
export const CHANGE_ANSWER_STATE = 'CHANGE_ANSWER_STATE';
export const FINISH_QUIZ = 'FINISH_QUIZ';
export const NEXT_QUESTION = 'NEXT_QUESTION';