import React from 'react';
import classes from './Question.module.scss';

const Question2 = () => {
    return (
        <pre className={classes.Question} style={{color: '#000020', background: '#f6f8ff'}}><span style={{color: '#004a43'}}>&lt;!DOCTYPE html&gt;</span>{"\n"}<span style={{color: '#0057a6'}}>&lt;</span><span style={{color: '#200080', fontWeight: 'bold'}}>html</span><span style={{color: '#474796'}}> </span><span style={{color: '#074726'}}>lang</span><span style={{color: '#308080'}}>=</span><span style={{color: '#1060b6'}}>'en'</span><span style={{color: '#0057a6'}}>&gt;</span>{"\n"}{"    "}<span style={{color: '#0057a6'}}>&lt;</span><span style={{color: '#200080', fontWeight: 'bold'}}>head</span><span style={{color: '#0057a6'}}>&gt;</span>{"\n"}{"        "}<span style={{color: '#0057a6'}}>&lt;</span><span style={{color: '#200080', fontWeight: 'bold'}}>title</span><span style={{color: '#0057a6'}}>&gt;</span>Document<span style={{color: '#0057a6'}}>&lt;/</span><span style={{color: '#200080', fontWeight: 'bold'}}>title</span><span style={{color: '#0057a6'}}>&gt;</span>{"\n"}{"    "}<span style={{color: '#0057a6'}}>&lt;/</span><span style={{color: '#200080', fontWeight: 'bold'}}>head</span><span style={{color: '#0057a6'}}>&gt;</span>{"\n"}{"    "}<span style={{color: '#0057a6'}}>&lt;</span><span style={{color: '#200080', fontWeight: 'bold'}}>body</span><span style={{color: '#0057a6'}}>&gt;</span>{"\n"}{"        "}<span style={{color: '#0057a6'}}>&lt;</span><span style={{color: '#200080', fontWeight: 'bold'}}>img</span><span style={{color: '#474796'}}> </span><span style={{color: '#074726'}}>src</span><span style={{color: '#308080'}}>=</span><span style={{color: '#1060b6'}}>'./img.jpg'</span><span style={{color: '#474796'}}> </span><span style={{color: '#074726'}}>alt</span><span style={{color: '#308080'}}>=</span><span style={{color: '#1060b6'}}>'img'</span><span style={{color: '#0057a6'}}>&gt;</span>{"\n"}{"    "}<span style={{color: '#0057a6'}}>&lt;/</span><span style={{color: '#200080', fontWeight: 'bold'}}>body</span><span style={{color: '#0057a6'}}>&gt;</span>{"\n"}<span style={{color: '#0057a6'}}>&lt;/</span><span style={{color: '#200080', fontWeight: 'bold'}}>html</span><span style={{color: '#0057a6'}}>&gt;</span>{"\n"}</pre>
    );
};

export default Question2;